server:
  port: 0

spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 119.45.221.206:8848

    sentinel:
      transport:
        #指定sentinel控制台地址
#        dashboard: 119.45.221.206:8080
        dashboard: localhost:8080


  datasource:
    url: jdbc:mysql://39.98.143.134:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimumIdle: 10
      maximumPoolSize: 100
      maxLifetime: 1800000
      idleTimeout: 600000
      CONNECTIONTIMEOUT: 30000

# Mybatis驼峰式开启，可省略
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

# Spring Boot监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 细粒度的配置方式，不支持全局配置文件式写法，Ribbon全局配置只能用Java代码配置
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon饥饿加载，提升首次访问速度
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# feign配置日志
logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug，否则都不会打印
    com.mqxu.contentcenter.feignclient.UserCenterFeignClient: debug

# feign细粒度配置
feign:
  client:
    config:
     #想要调用的微服务名称
      user-center:
        loggerLevel: full

#feign:
#  client:
#    config:
#     #全局配置
#      default:
#        loggerLevel: full

rocketmq:
#  name-server: 119.45.221.206:9876
  name-server: 39.98.143.134:9876
  producer:
    # 必须指定group
    group: test-group