server:
  port: 8888
spring:
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 10e5a9a3-05ce-457f-b2a3-02bcfe1b512d

  datasource:
    url: jdbc:mysql://39.98.143.134:3306/content_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

#feign:
#  client:
#    config:
#      # 全局配置
#      default:
#        loggerLevel: full
#  httpclient:
#    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
#    enabled: true
#    # feign的最大连接数
#    max-connections: 200
#    # feign单个路径的最大连接数
#    max-connections-per-route: 50