server:
  port: 8002
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://39.98.143.134:3306/content_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver