server:
  port: 8888

spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 39.98.143.134:8848

    sentinel:
      transport:
        #指定sentinel控制台地址
#        dashboard: 119.45.221.206:8080
        dashboard: localhost:8080


  datasource:
    url: jdbc:mysql://39.98.143.134:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: NjuitScs.123
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000

# Mybatis驼峰式开启，可省略
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

# Spring Boot监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 细粒度的配置方式，不支持全局配置文件式写法，Ribbon全局配置只能用Java代码配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon饥饿加载，提升首次访问速度
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# feign配置日志
logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug，否则都不会打印
    com.mqxu.contentcenter.feignclient.UserCenterFeignClient: debug

# feign细粒度配置
#feign:
#  client:
#    config:
#     #想要调用的微服务名称
#      user-center:
#        loggerLevel: full

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.mqxu.contentcenter.feignclient.interceptor.TokenInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

rocketmq:
  name-server: 119.45.221.206:9876
  producer:
    # 必须指定group
    group: test-group

