server:
  port: 0
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 119.45.221.206:8848
#        namespace: 10e5a9a3-05ce-457f-b2a3-02bcfe1b512d

  #        metadata:
#          instance: cc
#          hello: world
#          version: 1.0

  datasource:
    url: jdbc:mysql://39.98.143.134:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimumIdle: 10
      maximumPoolSize: 100
      maxLifetime: 1800000
      idleTimeout: 600000
      CONNECTIONTIMEOUT: 30000



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

rocketmq:
#  name-server: 119.45.221.206:9876
  name-server: 39.98.143.134:9876