server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 39.98.143.134:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_route1
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: path_route2
          uri: lb://content-center
          predicates:
            - Path=/shares/**
        - id: path_route3
          uri: lb://content-center
          predicates:
            - Path=/notices/**
#        - id: between_route
#          uri: lb://user-center
#          predicates:
##            - Path=/**
#            - TimeBetween=上午11:20,下午5:00
              # 当且仅当带有名为X-Request-Id，并且值符合正则\d+的Header时，才会转发到用户微服务
              # 如Header满足条件，则访问http://localhost:8040/** -> user-center/**
              # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
#              - Header=X-Request-Id, \d+

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: trace